config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1, defaults: { format: 'json' } do
      get 'greetings', to: 'greetings#index'
    end
  end

   # react routes

   get '*page', to: 'static#index', constraints: ->(req) do
    !req.xhr? && req.format.html?
  end

  # Defines the root path route ("/")
  root "static#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/greeting.rb
class Greeting < ApplicationRecord
end

app/controllers/api/v1/greetings_controller.rb
class Api::V1::GreetingsController < ApplicationController
  before_action :set_greeting, only: %i[show edit update destroy]

  # GET /greetings or /greetings.json
  def index
    @greeting = Greeting.order('RANDOM()').first
    if @greeting
      render json: { status: 'SUCCESS', data: { greeting: @greeting }, message: 'Greeting loaded successfully' },
             status: :ok
    else
      render json: { success: false, errors: 'Oops, Something went wrong!' }, status: :unprocessable_entity
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/greetings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Greetings</h1>

<div id="greetings">
  <% @greetings.each do |greeting| %>
    <%= render greeting %>
    <p>
      <%= link_to "Show this greeting", greeting %>
    </p>
  <% end %>
</div>

<%= link_to "New greeting", new_greeting_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloRailsReact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>